[package]
name = "pxtwitter-mosaic"
authors = ["Antonio32A"]
license = "MIT"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
reqwest = "0.11.11"
image = "0.24.2"
futures = "0.3.21"
itertools = "0.10.2"
webp = "0.2.2"
