name: Build Release binaries

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-gnu

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        default: true
    
    - name: Install dependencies for cross-compilation
      if: matrix.target == 'aarch64-unknown-linux-gnu'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu


    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --target ${{ matrix.target }}

    - name: Upload Release Asset
      uses: actions/upload-artifact@v2
      with:
        name: mosaic-${{ matrix.target }}
        path: target/${{ matrix.target }}/release/mosaic${{ matrix.target == 'x86_64-pc-windows-gnu' && '.exe' || '' }}


  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Artifacts
      uses: actions/download-artifact@v2

    - name: Upload Release Asset
    - name: Create GitHub Release and Upload Assets
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: |
          target/${{ matrix.target }}/release/mosaic${{ matrix.target == 'x86_64-pc-windows-gnu' && '.exe' || '' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

